/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin;

import CommonTasks.RemovingData;
import UI.ViewOrders;
import UI.Admin.AddItem;
import UI.ChangePssword;
import UI.ViewItems;
import UI.Login;
import UI.UpdateUserProfile;
import UI.ViewMeals;
import java.awt.Color;

/**
 *
 * @author Chamika
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
        profileSOptions.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addAdmins = new javax.swing.JButton();
        addMeals = new javax.swing.JButton();
        viewMeals = new javax.swing.JButton();
        addItem = new javax.swing.JButton();
        viewItems = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        profileSOptions = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        profileSettings = new javax.swing.JLabel();
        viewOrders = new javax.swing.JButton();
        viewUsers = new javax.swing.JButton();
        img = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addAdmins.setBackground(new java.awt.Color(0, 0, 0));
        addAdmins.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addAdmins.setForeground(new java.awt.Color(255, 255, 255));
        addAdmins.setText("Add Admins");
        addAdmins.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addAdmins.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAdminsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addAdminsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addAdminsMouseExited(evt);
            }
        });
        addAdmins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminsActionPerformed(evt);
            }
        });
        jPanel1.add(addAdmins, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 320, 35));

        addMeals.setBackground(new java.awt.Color(0, 0, 0));
        addMeals.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addMeals.setForeground(new java.awt.Color(255, 255, 255));
        addMeals.setText("Add Meals");
        addMeals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMealsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMealsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMealsMouseExited(evt);
            }
        });
        addMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMealsActionPerformed(evt);
            }
        });
        jPanel1.add(addMeals, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 220, 35));

        viewMeals.setBackground(new java.awt.Color(0, 0, 0));
        viewMeals.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        viewMeals.setForeground(new java.awt.Color(255, 255, 255));
        viewMeals.setText("View Meals");
        viewMeals.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewMealsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewMealsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewMealsMouseExited(evt);
            }
        });
        jPanel1.add(viewMeals, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 320, 35));

        addItem.setBackground(new java.awt.Color(0, 0, 0));
        addItem.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        addItem.setForeground(new java.awt.Color(255, 255, 255));
        addItem.setText("Add Items");
        addItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addItemMouseExited(evt);
            }
        });
        addItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemActionPerformed(evt);
            }
        });
        jPanel1.add(addItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 220, 35));

        viewItems.setBackground(new java.awt.Color(0, 0, 0));
        viewItems.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        viewItems.setForeground(new java.awt.Color(255, 255, 255));
        viewItems.setText("View Items");
        viewItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewItemsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewItemsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewItemsMouseExited(evt);
            }
        });
        viewItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewItemsActionPerformed(evt);
            }
        });
        jPanel1.add(viewItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 320, 35));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 260, 50));

        title.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        title.setText("Admin Dashboard");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 440, -1));

        profileSOptions.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("           Update profile");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("         Change Password");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("      Delete My Account");
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });

        javax.swing.GroupLayout profileSOptionsLayout = new javax.swing.GroupLayout(profileSOptions);
        profileSOptions.setLayout(profileSOptionsLayout);
        profileSOptionsLayout.setHorizontalGroup(
            profileSOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileSOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(profileSOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addGroup(profileSOptionsLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)))
                .addContainerGap())
        );
        profileSOptionsLayout.setVerticalGroup(
            profileSOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileSOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(profileSOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, 220, 120));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeicon.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        profileSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Webp.net-resizeimage (1).png"))); // NOI18N
        profileSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileSettingsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileSettingsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 841, Short.MAX_VALUE)
                .addComponent(profileSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(profileSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 30));

        viewOrders.setBackground(new java.awt.Color(0, 0, 0));
        viewOrders.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        viewOrders.setForeground(new java.awt.Color(255, 255, 255));
        viewOrders.setText("View Orders");
        viewOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewOrdersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewOrdersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewOrdersMouseExited(evt);
            }
        });
        viewOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewOrdersActionPerformed(evt);
            }
        });
        jPanel1.add(viewOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 230, 35));

        viewUsers.setBackground(new java.awt.Color(0, 0, 0));
        viewUsers.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        viewUsers.setForeground(new java.awt.Color(255, 255, 255));
        viewUsers.setText("View Users");
        viewUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewUsersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewUsersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewUsersMouseExited(evt);
            }
        });
        viewUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUsersActionPerformed(evt);
            }
        });
        jPanel1.add(viewUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 230, 35));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.jpeg"))); // NOI18N
        img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgMouseClicked(evt);
            }
        });
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addAdminsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addAdminsActionPerformed

    private void addMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMealsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addMealsActionPerformed

    private void addItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addItemActionPerformed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login log=new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void addAdminsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAdminsMouseClicked
        AdminRegistration admin=new AdminRegistration();
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addAdminsMouseClicked

    private void addAdminsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAdminsMouseEntered
       addAdmins.setBackground(Color.white);
       addAdmins.setForeground(Color.black);
    }//GEN-LAST:event_addAdminsMouseEntered

    private void addAdminsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAdminsMouseExited
       addAdmins.setBackground(Color.black);
       addAdmins.setForeground(Color.white);
    }//GEN-LAST:event_addAdminsMouseExited

    private void addMealsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMealsMouseClicked
        AddMeals meal=new AddMeals();
        meal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addMealsMouseClicked

    private void addMealsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMealsMouseEntered
        addMeals.setBackground(Color.white);
        addMeals.setForeground(Color.black);
    }//GEN-LAST:event_addMealsMouseEntered

    private void addMealsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMealsMouseExited
       addMeals.setBackground(Color.black);
       addMeals.setForeground(Color.white);
    }//GEN-LAST:event_addMealsMouseExited

    private void viewMealsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMealsMouseEntered
       viewMeals.setBackground(Color.white);
       viewMeals.setForeground(Color.black);
    }//GEN-LAST:event_viewMealsMouseEntered

    private void viewMealsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMealsMouseExited
       viewMeals.setBackground(Color.black);
       viewMeals.setForeground(Color.white);
    }//GEN-LAST:event_viewMealsMouseExited

    private void addItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemMouseEntered
       addItem.setBackground(Color.white);
       addItem.setForeground(Color.black);
    }//GEN-LAST:event_addItemMouseEntered

    private void addItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemMouseExited
       addItem.setBackground(Color.black);
       addItem.setForeground(Color.white);
    }//GEN-LAST:event_addItemMouseExited

    private void viewItemsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewItemsMouseEntered
       viewItems.setBackground(Color.white);
       viewItems.setForeground(Color.black);
    }//GEN-LAST:event_viewItemsMouseEntered

    private void viewItemsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewItemsMouseExited
       viewItems.setBackground(Color.black);
       viewItems.setForeground(Color.white);
    }//GEN-LAST:event_viewItemsMouseExited

    private void viewMealsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMealsMouseClicked
        ViewMeals mealList=new ViewMeals();
        mealList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewMealsMouseClicked

    private void addItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addItemMouseClicked
        AddItem item =new AddItem();
        item.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addItemMouseClicked

    private void viewItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewItemsMouseClicked
        ViewItems view=new ViewItems();
        view.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_viewItemsMouseClicked

    private void profileSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileSettingsMouseExited
        //profileSOptions.setVisible(false);
    }//GEN-LAST:event_profileSettingsMouseExited

    private void profileSettingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileSettingsMouseClicked
        profileSOptions.setVisible(true);
    }//GEN-LAST:event_profileSettingsMouseClicked

    private void profileSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileSettingsMouseEntered
        profileSOptions.setVisible(false);
    }//GEN-LAST:event_profileSettingsMouseEntered

    private void imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMouseClicked
        profileSOptions.setVisible(false);
    }//GEN-LAST:event_imgMouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setBackground(Color.white);
        jLabel2.setForeground(Color.black);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setBackground(Color.black);
        jLabel2.setForeground(Color.white);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setBackground(Color.white);
        jLabel3.setForeground(Color.black);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setBackground(Color.black);
        jLabel3.setForeground(Color.white);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        UpdateUserProfile updateUserProfile=new UpdateUserProfile();
        updateUserProfile.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        ChangePssword pwd=new ChangePssword();
        pwd.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void viewOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewOrdersMouseClicked
        ViewOrders approveOrders=new ViewOrders();
        approveOrders.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewOrdersMouseClicked

    private void viewOrdersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewOrdersMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_viewOrdersMouseEntered

    private void viewOrdersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewOrdersMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_viewOrdersMouseExited

    private void viewItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewItemsActionPerformed

    private void viewOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewOrdersActionPerformed

    private void viewUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewUsersMouseClicked
       UserList userList=new UserList();
       userList.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_viewUsersMouseClicked

    private void viewUsersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewUsersMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_viewUsersMouseEntered

    private void viewUsersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewUsersMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_viewUsersMouseExited

    private void viewUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUsersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewUsersActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        RemovingData removingData=new RemovingData();
        removingData.removeAdmin(Login.userID);
        Login login=new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdmins;
    private javax.swing.JButton addItem;
    private javax.swing.JButton addMeals;
    private javax.swing.JLabel close;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel profileSOptions;
    private javax.swing.JLabel profileSettings;
    private javax.swing.JLabel title;
    private javax.swing.JButton viewItems;
    private javax.swing.JButton viewMeals;
    private javax.swing.JButton viewOrders;
    private javax.swing.JButton viewUsers;
    // End of variables declaration//GEN-END:variables
}
