/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin;

import CommonTasks.RemovingData;
import UI.ViewOrders;
import HybernetSession.HybernetSessionFctory;
import Pojos.Item;
import Pojos.Meals;
import Pojos.OrderDetails;
import Pojos.Orders;
import UI.ItemDescriptions;
import UI.Login;
import CommonTasks.RetrieveData;
import CommonTasks.UpdateData;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.CallableStatement;
import java.sql.Types;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Chamika
 */
public class OrderInfo extends javax.swing.JFrame {

    int height=60,odID,theight=60;
    String uId="",oDstat="";
    Session oDsession;
    Session osession;
    public OrderInfo() {
        initComponents();
//        fill();
//        setTitle();
        
    }

    public OrderInfo(int odID) {
        this.odID=odID;
        initComponents();
        fill();
        setTitle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        background = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        imgLayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(background);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 930, 380));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("Orders");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 320, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 50));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeicon.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 883, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 30));

        imgLayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.jpeg"))); // NOI18N
        jPanel1.add(imgLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        ViewOrders viewOrders=new ViewOrders();
        viewOrders.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login log=new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel background;
    private javax.swing.JLabel close;
    private javax.swing.JLabel imgLayer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    // End of variables declaration//GEN-END:variables

    public void fill(){
        int height=350;
        background.removeAll();
        String n="";
        
        

        if (Login.userType.equals("user")){
            oDsession=HybernetSession.HybernetSessionFctoryUser.getSessionFactory().openSession();
        }else if (Login.userType.equals("admin")){
            oDsession=HybernetSession.HybernetSessionFctory.getSessionFactory().openSession();
        }
        
        Transaction dt=oDsession.beginTransaction();
        
        String odSql="From OrderDetails";
        Query odquery=oDsession.createQuery(odSql);
        List<OrderDetails> odList=odquery.list();
        
        for(Iterator<OrderDetails> odIterator=odList.iterator();odIterator.hasNext();){
            
            OrderDetails odDetails=odIterator.next();
            if(odDetails.getOrderId()==odID){
                JPanel addPanal = new JPanel();
                JLabel itemName = new JLabel();
                JLabel quantity = new JLabel();
                JLabel unitPrice = new JLabel();
                JLabel subTot = new JLabel();

                addPanal.setBackground(new java.awt.Color(102,204,255));
                addPanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                itemName.setBackground(new java.awt.Color(204, 255, 255));
                itemName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                
                RetrieveData retrieveData=new RetrieveData();
                n=retrieveData.getiNames(odDetails.getItemId(), odDetails.getType());
                        
                

                itemName.setText(n);
                itemName.setOpaque(true);


                quantity.setBackground(new java.awt.Color(204, 255, 255));
                quantity.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                quantity.setText(String.valueOf(odDetails.getQuantity()));
                quantity.setOpaque(true);

                unitPrice.setBackground(new java.awt.Color(204, 255, 255));
                unitPrice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                unitPrice.setText(String.valueOf(odDetails.getUnitPrice()));
                unitPrice.setOpaque(true);

                subTot.setBackground(new java.awt.Color(204, 255, 255));
                subTot.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                subTot.setText(String.valueOf(odDetails.getSubTotal()));
                subTot.setOpaque(true);

                addPanal.add(itemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 40));
                addPanal.add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 150, 40));
                addPanal.add(unitPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 150, 40));
                addPanal.add(subTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 200, 40));
                //addPanal.add(moreInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 200, 40));

                background.add(addPanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40,height , 850, 60));
                height=height+70;
                
                
            } 
            
            
        }
       // oDsession.close();
        if (Login.userType.equals("user")){
            osession=HybernetSession.HybernetSessionFctoryUser.getSessionFactory().openSession();
        }else if (Login.userType.equals("admin")){
            osession=HybernetSession.HybernetSessionFctory.getSessionFactory().openSession();
        }
        
        Transaction t=osession.beginTransaction();
        String osql="From Orders";
        Query oquery=osession.createQuery(osql);
        List<Orders> oList=oquery.list();
        String dLocation="",dDate="",dstat = "";
        Float total = null;
        for(Iterator<Orders> oIterator=oList.iterator();oIterator.hasNext();){
            Orders o=oIterator.next();
            if (odID==o.getOrderId()){
                if (o.getDeliveryRequirement().equals("Yes")){
                    dLocation=o.getDeliveryLocation();
                    dDate=o.getDateToBeDelivered();
                }else if (o.getDeliveryRequirement().equals("No")){
                    dstat="Delivery not requested.";
                }
                total=o.getTotal();
                oDstat=o.getOrderStatus();
                uId=o.getUserId();
            }
            
        }
        //osession.close();
        
        height=height+20;
        
        JPanel addPanal2 = new JPanel();
        JLabel l1=new JLabel();
        JLabel l2=new JLabel();
        JLabel l3=new JLabel();
        JLabel l4=new JLabel();
        JLabel l5=new JLabel();
        JLabel delLo=new JLabel();
        JLabel delD=new JLabel();
        JLabel tot=new JLabel();
        JLabel delst=new JLabel();
        JLabel OiD=new JLabel();
        JPanel addPanal3=new JPanel();
        JButton confirm=new JButton();
        JButton reject=new JButton();
        JButton dispatched=new JButton();
        JButton cancel=new JButton();
       // JButton reject=new JButton();
        
        
        addPanal2.setBackground(new java.awt.Color(255,255,255));
        addPanal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        addPanal3.setBackground(new java.awt.Color(255,255,255));
        addPanal3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        
        
        //confirm.setBackground(new java.awt.Color(255, 255, 255));
        confirm.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        confirm.setText("Confirm Order");
        confirm.setOpaque(true);
        
        dispatched.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dispatched.setText("Order Dispached");
        dispatched.setOpaque(true);
        
        reject.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        reject.setText("Reject Order");
        reject.setOpaque(true);
        
        l1.setBackground(new java.awt.Color(255, 255, 255));
        l1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l1.setText("Delivery Location :");
        l1.setOpaque(true);
        
        
        l2.setBackground(new java.awt.Color(255, 255, 255));
        l2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l2.setText("Date To Be Delivered :");
        l2.setOpaque(true);
        
        l3.setBackground(new java.awt.Color(255, 255, 255));
        l3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l3.setText("Total Billed Value :");
        l3.setOpaque(true);
        
        l4.setBackground(new java.awt.Color(255, 255, 255));
        l4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l4.setText("Order Id :");
        l4.setOpaque(true);
        
        l5.setBackground(new java.awt.Color(255, 255, 255));
        l5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        l5.setText("Order Status :");
        l5.setOpaque(true);
        
        delLo.setBackground(new java.awt.Color(255, 255, 255));
        delLo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        
        delLo.setOpaque(true);
        
        delD.setBackground(new java.awt.Color(255, 255, 255));
        delD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delD.setOpaque(true);
        
        delst.setBackground(new java.awt.Color(255, 255, 255));
        delst.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        delst.setText(oDstat);
        delst.setOpaque(true);
        
        cancel.setBackground(new java.awt.Color(255, 255, 255));
        cancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        cancel.setText("Cancel Order");
        cancel.setOpaque(true);
        
        tot.setBackground(new java.awt.Color(255, 255, 255));
        tot.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tot.setText(String.valueOf(total));
        tot.setOpaque(true);
        
        OiD.setBackground(new java.awt.Color(255, 255, 255));
        OiD.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        OiD.setText(String.valueOf(odID));
        OiD.setOpaque(true);
        
        confirm.addMouseListener(new MouseAdapter() {                                
            @Override
            public void mouseClicked(MouseEvent e){
                RetrieveData retrieveData=new RetrieveData();
                
                String mail=retrieveData.getEmailAddress(uId);
                Email.SendEmails.sendInvoice(odID,mail);
  
                UpdateData updateData=new UpdateData();
                updateData.updateOrderStat(odID,"Confirmed");
                
                updateData.getDataToBeUpdated(odID);
                ViewOrders approveOrders=new ViewOrders();
                approveOrders.setVisible(true);
                FrameDispose();


            }
        });
        
        reject.addMouseListener(new MouseAdapter() {                                
            @Override
            public void mouseClicked(MouseEvent e){
                
                JFrame frame = new JFrame();
                String reason = JOptionPane.showInputDialog(frame, "Enter the reason to reject :");
                RetrieveData retrieveData=new RetrieveData();
                
                String mail=retrieveData.getEmailAddress(uId);
                Email.SendEmails.sendOrderRejectionAlert(odID,mail,reason);
                UpdateData updateData=new UpdateData();
                updateData.updateOrderStat(odID, "Rejected");
                ViewOrders approveOrders=new ViewOrders();
                approveOrders.setVisible(true);
                FrameDispose();
                


            }
        });
        
        dispatched.addMouseListener(new MouseAdapter() {                                
            @Override
            public void mouseClicked(MouseEvent e){
                UpdateData updateData=new UpdateData();
                updateData.updateOrderStat(odID, "Dispatched");
                ViewOrders approveOrders=new ViewOrders();
                approveOrders.setVisible(true);
                FrameDispose();
                


            }
        });
        //cancel orders
        cancel.addMouseListener(new MouseAdapter() {                                
            @Override
            public void mouseClicked(MouseEvent e){
                if (oDstat.equals("Pending")){
                    RemovingData removingData=new RemovingData();
                    removingData.removeOrder(odID);
                    ViewOrders viewOrders=new ViewOrders();
                    viewOrders.setVisible(true);
                    FrameDispose();
                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "Sorry, You cannot cancel this order. ", "Error", JOptionPane.ERROR_MESSAGE);
                }
                
                


            }
        });
        
        
        addPanal2.add(l4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, 40));
        addPanal2.add(OiD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 200, 40));
        if (dstat.equals("Delivery not requested.")){
            delLo.setText("Delivery facility is not Requested.");
            addPanal2.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, 40));
            addPanal2.add(delLo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 600, 40));
        }
        else{
            delLo.setText(dLocation);
            delD.setText(dDate);
            addPanal2.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 200, 40));
            addPanal2.add(delLo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 600, 40));
            addPanal2.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, 40));
            addPanal2.add(delD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 600, 40));
            
        }
        
        
        addPanal2.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 200, 40));
        addPanal2.add(tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 600, 40));
        
        addPanal2.add(l5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 200, 40));
        addPanal2.add(delst, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 600, 40));
        background.add(addPanal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40,0 , 850, 270));
        
        if (Login.userType.equals("admin")){
            //System.out.println("oDstat: "+oDstat);
            if (oDstat.equals("Pending")){
                addPanal3.add(confirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10 , 200, 40));
                addPanal3.add(reject, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10 , 200, 40));

            }else if (oDstat.equals("Confirmed")){
                confirm.setVisible(false);
                reject.setVisible(false);
                addPanal3.add(dispatched, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10 , 200, 40));
            }

            
 
            
        }
        
        else if(Login.userType.equals("user")){
            addPanal3.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10 , 200, 40));
        }
        background.add(addPanal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40,height , 850, 100));
        
        
    }
    
    
    public void setTitle(){
        JPanel titlePanal = new JPanel();
        JLabel titleItem1 = new JLabel();
        JLabel titleItem2 = new JLabel();
        JLabel titleItem3 = new JLabel();
        JLabel titleItem4 = new JLabel();
        JLabel titleItem5 = new JLabel();
        JLabel titleItem6 = new JLabel();

        titlePanal.setBackground(new java.awt.Color(255, 255, 255));
        titlePanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleItem1.setBackground(new java.awt.Color(102, 204, 255));
        titleItem1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titleItem1.setText("      Item Name");
        titleItem1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        titleItem1.setOpaque(true);
        titlePanal.add(titleItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 300, 40));

        titleItem2.setBackground(new java.awt.Color(102, 204, 255));
        titleItem2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titleItem2.setText("         quantity");
        titleItem2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        titleItem2.setOpaque(true);
        titlePanal.add(titleItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 150, 40));

        titleItem3.setBackground(new java.awt.Color(102, 204, 255));
        titleItem3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titleItem3.setText("    Unit Price");
        titleItem3.setOpaque(true);
        titlePanal.add(titleItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 150, 40));
        
        titleItem4.setBackground(new java.awt.Color(102, 204, 255));
        titleItem4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titleItem4.setText("  Sub Total");
        titleItem4.setOpaque(true);
        titlePanal.add(titleItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 200, 40));
        
       background.add(titlePanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40,280, 850, 60));
    }
    

     
    public void FrameDispose(){
        this.dispose();
    }
}
