/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.Admin;

import Pojos.MonthlySales;
import Pojos.Sales;
import Pojos.YearlySales;
import UI.Login;
import UI.User.UserDashboard;
import java.util.Iterator;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Chamika
 */
public class ViewSales extends javax.swing.JFrame {

    int dheight=10,height,sheight,yheight;
    public ViewSales() {
        initComponents();
        fill();
        addTitle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        background = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        imgLayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(background);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 930, 370));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("Sales");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 320, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 50));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeicon.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 883, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 30));

        imgLayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.jpeg"))); // NOI18N
        jPanel1.add(imgLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        if (Login.userType.equals("admin")){
            AdminDashboard adminDashboard=new AdminDashboard();
            adminDashboard.setVisible(true);
            this.dispose();
        }
        else if (Login.userType.equals("user")){
            UserDashboard userDashboard=new UserDashboard();
            userDashboard.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login log=new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel background;
    private javax.swing.JLabel close;
    private javax.swing.JLabel imgLayer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    // End of variables declaration//GEN-END:variables

    public void fill(){
        background.removeAll();
        dheight=140;
        sheight=140;
        yheight=140;
       
        
//        JPanel monthlyP = new JPanel();
//        JLabel month = new JLabel();
//        JLabel mamount = new JLabel();
//        JPanel annualyP = new JPanel();
//        JLabel year = new JLabel();
//        JLabel yamount = new JLabel();
        
        
        
        
        
        Session dsession=HybernetSession.HybernetSessionFctory.getSessionFactory().openSession();
        Transaction dt=dsession.beginTransaction();
        
        String dsql="From Sales";
        Query dquery=dsession.createQuery(dsql);
        List<Sales> slist=dquery.list();
        
        for(Iterator<Sales>dIterator=slist.iterator();dIterator.hasNext();){
            Sales sales=dIterator.next();
            JPanel addPanal1 = new JPanel();
            JPanel dailyP = new JPanel();
            JLabel date = new JLabel();
            JLabel damount = new JLabel();
            
            System.out.println(sales.getDate());
            
            addPanal1.setBackground(new java.awt.Color(255, 255, 255));
            
            addPanal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            addPanal1.setBackground(new java.awt.Color(255, 255, 255));
            addPanal1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            dailyP.setBackground(new java.awt.Color(0, 153, 153));
            dailyP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            date.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
            date.setText(sales.getDate().toString());
            date.setOpaque(true);
            dailyP.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 102, 27));

            damount.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
            damount.setText(String.valueOf(sales.getAmount()));
            damount.setOpaque(true);
            dailyP.add(damount, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 13, 136, 27));

            addPanal1.add(dailyP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 50));

            background.add(addPanal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, dheight, 300, 60));

            dheight=dheight+60;
           
            background.setVisible(false);
            background.setVisible(true);
        }
        
        
        
        Session ssession=HybernetSession.HybernetSessionFctory.getSessionFactory().openSession();
        Transaction st=ssession.beginTransaction();
        
        String ssql="From MonthlySales";
        Query squery=dsession.createQuery(ssql);
        List<MonthlySales> mslist=squery.list();
        
        for(Iterator<MonthlySales>dIterator=mslist.iterator();dIterator.hasNext();){
            MonthlySales monthlySales=dIterator.next();
            JPanel addPanal2 = new JPanel();
            JPanel dailyP2 = new JPanel();
            JLabel date2 = new JLabel();
            JLabel damount2 = new JLabel();

            addPanal2.setBackground(new java.awt.Color(255, 255, 255));
            addPanal2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            dailyP2.setBackground(new java.awt.Color(0, 153, 153));
            dailyP2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            date2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
            date2.setText(String.valueOf(monthlySales.getMonth()));
            date2.setOpaque(true);
            dailyP2.add(date2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 102, 27));

            damount2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
            damount2.setText(String.valueOf(monthlySales.getAmount()));
            damount2.setOpaque(true);
            dailyP2.add(damount2, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 13, 136, 27));

            addPanal2.add(dailyP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 50));

            background.add(addPanal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, sheight, 300, 60));
            sheight=sheight+60;
            background.setVisible(false);
            background.setVisible(true);
          
            
        }
        
        Session ysession=HybernetSession.HybernetSessionFctory.getSessionFactory().openSession();
        Transaction yt=ysession.beginTransaction();
        
        String ysql="From YearlySales";
        Query yquery=dsession.createQuery(ysql);
        List<YearlySales> ylist=yquery.list();
        
        for(Iterator<YearlySales>yIterator=ylist.iterator();yIterator.hasNext();){
            YearlySales yearlySales=yIterator.next();
            JPanel addPanal3 = new JPanel();
            JPanel dailyP3 = new JPanel();
            JLabel date3 = new JLabel();
            JLabel damount3 = new JLabel();
            addPanal3.setBackground(new java.awt.Color(255, 255, 255));
            addPanal3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            dailyP3.setBackground(new java.awt.Color(0, 153, 153));
            dailyP3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            date3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
            date3.setText(String.valueOf(yearlySales.getYear()));
            date3.setOpaque(true);
            dailyP3.add(date3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 102, 27));

            damount3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
            damount3.setText(String.valueOf(yearlySales.getAmount()));
            damount3.setOpaque(true);
            dailyP3.add(damount3, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 13, 136, 27));

            addPanal3.add(dailyP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 50));

            background.add(addPanal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, yheight, 300, 60));
            yheight=yheight+60;
            background.setVisible(false);
            background.setVisible(true);
        }
        
        
    }
    
    public void addTitle(){
        JPanel titlePanal = new JPanel();
        JPanel jPanel4 = new JPanel();
        JLabel jLabel1 = new JLabel();
        JPanel jPanel5 = new JPanel();
        JLabel jLabel3 = new JLabel();
        JPanel jPanel6 = new JPanel();
        JLabel jLabel4 = new JLabel();
        JPanel jPanel7 = new JPanel();
        JLabel jLabel5 = new JLabel();
        JLabel jLabel6 = new JLabel();
        JPanel jPanel10 = new JPanel();
        JLabel jLabel7 = new JLabel();
        JLabel jLabel8 = new JLabel();
        JPanel jPanel11 = new JPanel();
        JLabel jLabel9 = new JLabel();
        JLabel jLabel10 = new JLabel();
        
        titlePanal.setBackground(new java.awt.Color(255, 255, 255));
        titlePanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Daily Sales");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 13, -1, -1));

        titlePanal.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 50));
        
        

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("Monthly Sales");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 13, -1, -1));

        titlePanal.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 280, 50));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setText("Annual Sales");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 13, -1, -1));

        titlePanal.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 280, 50));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("      Date");
        jLabel5.setOpaque(true);
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 102, 27));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("     Amount");
        jLabel6.setOpaque(true);
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 13, 136, 27));

        titlePanal.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 280, 50));

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("    Month");
        jLabel7.setOpaque(true);
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 102, 27));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("     Amount");
        jLabel8.setOpaque(true);
        jPanel10.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 13, 136, 27));

        titlePanal.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 280, 50));

        jPanel11.setBackground(new java.awt.Color(0, 153, 153));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("    Year");
        jLabel9.setOpaque(true);
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 102, 27));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("     Amount");
        jLabel10.setOpaque(true);
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 13, 136, 27));

        titlePanal.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 280, 50));

        background.add(titlePanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 910, 130));
        
    }
    
    
}
