/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import CommonTasks.RetrieveData;
import HybernetSession.HybernetSessionFctory;
import HybernetSession.HybernetSessionFctoryUser;
import Pojos.Admin;
import Pojos.Studentnstaff;
import UI.Admin.AdminDashboard;
import UI.User.UserDashboard;
import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Chamika
 */
public class ChangePssword extends javax.swing.JFrame {

    RetrieveData retrieveData=new RetrieveData();
    public ChangePssword() {
        initComponents();
        id.setText(Login.userID);
        hideOld.setVisible(false);
        hidenew.setVisible(false);
        hidenew1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        newpwd = new javax.swing.JPasswordField();
        cnfmPwd = new javax.swing.JPasswordField();
        hideOld = new javax.swing.JLabel();
        hidenew = new javax.swing.JLabel();
        vnew = new javax.swing.JLabel();
        hidenew1 = new javax.swing.JLabel();
        vOld = new javax.swing.JLabel();
        vnew2 = new javax.swing.JLabel();
        oldPwd = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        title.setText("Change Password");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 440, -1));

        lbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl1.setText("Registration ID");
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 170, 30));

        lbl2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl2.setText("Old Password");
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 160, 20));

        lbl3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl3.setText("New Password");
        jPanel1.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        lbl4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl4.setText("Re type new Password");
        jPanel1.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        id.setEditable(false);
        id.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 320, -1));

        update.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));

        error.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 460, 30));

        newpwd.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jPanel1.add(newpwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 320, -1));

        cnfmPwd.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jPanel1.add(cnfmPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 320, -1));

        hideOld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invisible.jpg"))); // NOI18N
        hideOld.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hideOld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideOldMouseClicked(evt);
            }
        });
        jPanel1.add(hideOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 25, 25));

        hidenew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invisible.jpg"))); // NOI18N
        hidenew.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hidenew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidenewMouseClicked(evt);
            }
        });
        jPanel1.add(hidenew, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 25, 25));

        vnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visible.png"))); // NOI18N
        vnew.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        vnew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vnewMouseClicked(evt);
            }
        });
        jPanel1.add(vnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 25, 25));

        hidenew1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/invisible.jpg"))); // NOI18N
        hidenew1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hidenew1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hidenew1MouseClicked(evt);
            }
        });
        jPanel1.add(hidenew1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 25, 25));

        vOld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visible.png"))); // NOI18N
        vOld.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        vOld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vOldMouseClicked(evt);
            }
        });
        jPanel1.add(vOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 25, 25));

        vnew2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/visible.png"))); // NOI18N
        vnew2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        vnew2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vnew2MouseClicked(evt);
            }
        });
        jPanel1.add(vnew2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 25, 25));

        oldPwd.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jPanel1.add(oldPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 320, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeicon.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 883, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 50));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stafreg.jpg"))); // NOI18N
        img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imgMouseClicked(evt);
            }
        });
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
      Session usession;
        if (Login.userType.equals("user")){
            usession=HybernetSessionFctoryUser.getSessionFactory().openSession();
        }
        else{
            usession=HybernetSessionFctory.getSessionFactory().openSession();
        }
        
        Transaction ut=usession.beginTransaction();
        
        if (oldPwd.getPassword().equals("") || newpwd.getPassword().equals("") || cnfmPwd.getPassword().equals("")){
            error.setText("Please fill all the fields..");
        }
        
        else{   
            char [] Npass=newpwd.getPassword();
            String pwrd;
            pwrd = ("" + new String(Npass));
            char [] pass=oldPwd.getPassword();
            String Opwrd=("" + new String(pass));
            if (Arrays.equals(newpwd.getPassword(), cnfmPwd.getPassword())) {               
                error.setText("");
                if (Login.userType.equals("admin")){               
                    String usql="From Admin";
                    Query uquery=usession.createQuery(usql);
                    List<Admin> adminList=uquery.list();
                    for (Iterator<Admin> aIterator=adminList.iterator();aIterator.hasNext();){
                        Admin admin=aIterator.next();
                        if (admin.getAdminId().equals(Login.userID)){
                            if(Opwrd.equals(admin.getPassword())){
                                
                                String mail=admin.getEmail();
                                
                                //genearating random String
                                String generatedString=retrieveData.generateRandomString();
                                
                                Email.SendEmails.VerifyIdentity(generatedString,mail);
                                error.setText("Verification code will be sent to your email.....");
                                JFrame frame = new JFrame();
                                String rveri = JOptionPane.showInputDialog(frame, "We have send you a verification code to your email. Please enter the verification code :");

                                if (rveri!=null){
                                    error.setText("");
                                    if (rveri.equals(generatedString)){
                                        admin.setPassword(pwrd);
                                        usession.save(admin);
                                        usession.getTransaction().commit();
                                        JOptionPane.showMessageDialog(null, "Password updated successfully", "Successful", JOptionPane.INFORMATION_MESSAGE);
                                        AdminDashboard dash=new AdminDashboard();
                                        dash.setVisible(true);
                                        this.dispose();
                                    }
                                    else{
                                        error.setText("Invalid confirmation code");
                                    }

                                }

                            }
                            else{
                                error.setText("Old Password you entered is incorrect..");
                            }

                        }

                    }
                    
                }
                
                else if(Login.userType.equals("user")){
                    String usql="From Studentnstaff";
                    Query uquery=usession.createQuery(usql);
                    List<Studentnstaff> uList=uquery.list();
                    for (Iterator<Studentnstaff> uIterator=uList.iterator();uIterator.hasNext();){
                        Studentnstaff st=uIterator.next();
                        if (st.getRegNo().equals(Login.userID)){
                            if(Opwrd.equals(st.getPassword())){
                                
                                String mail=st.getEmail();
                                
                                String generatedString=retrieveData.generateRandomString();
                                
                                Email.SendEmails.VerifyIdentity(generatedString,mail);
                                error.setText("Verification code will be sent to your email.....");
                                JFrame frame = new JFrame();
                                String rveri = JOptionPane.showInputDialog(frame, "We have send you a verification code to your email. Please enter the verification code :");

                                if (rveri!=null){
                                    error.setText("");
                                    if (rveri.equals(generatedString)){
                                        st.setPassword(pwrd);
                                        usession.save(st);
                                        usession.getTransaction().commit();
                                        JOptionPane.showMessageDialog(null, "Password updated successfully", "Successful", JOptionPane.INFORMATION_MESSAGE);
                                        UserDashboard udash=new UserDashboard();
                                        udash.setVisible(true);
                                        this.dispose();
                                    }
                                    else{
                                        error.setText("Invalid confirmation code");
                                    }

                                }

                            }
                            else{
                                error.setText("Old Password you entered is incorrect..");
                            }

                        }

                    }
                    
                }
                
            }
            else{
                error.setText("Please recheck and re enter new password..");
                newpwd.setText("");
                cnfmPwd.setText("");
                
            }             
            
        }
        
    }//GEN-LAST:event_updateMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
        
    }//GEN-LAST:event_closeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login log=new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void vOldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vOldMouseClicked
        vOld.setVisible(false);
        hideOld.setVisible(true);
        oldPwd.setEchoChar((char)0);
        
        
    }//GEN-LAST:event_vOldMouseClicked

    private void hideOldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideOldMouseClicked
        vOld.setVisible(true);
        hideOld.setVisible(false);
        oldPwd.setEchoChar('*');
    }//GEN-LAST:event_hideOldMouseClicked

    private void hidenewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidenewMouseClicked
        vnew.setVisible(true);
        hidenew.setVisible(false);
        newpwd.setEchoChar('*');
    }//GEN-LAST:event_hidenewMouseClicked

    private void vnewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vnewMouseClicked
        vnew.setVisible(false);
        hidenew.setVisible(true);
        newpwd.setEchoChar((char)0);
    }//GEN-LAST:event_vnewMouseClicked

    private void hidenew1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hidenew1MouseClicked
        vnew2.setVisible(true);
        hidenew1.setVisible(false);
        cnfmPwd.setEchoChar('*');
    }//GEN-LAST:event_hidenew1MouseClicked

    private void imgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imgMouseClicked
        
    }//GEN-LAST:event_imgMouseClicked

    private void vnew2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vnew2MouseClicked
        vnew2.setVisible(false);
        hidenew1.setVisible(true);
        cnfmPwd.setEchoChar((char)0);
    }//GEN-LAST:event_vnew2MouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        if (Login.userType.equals("admin")){
            AdminDashboard adminDashboard=new AdminDashboard();
            adminDashboard.setVisible(true);
            this.dispose();
        }
        else if (Login.userType.equals("user")){
            UserDashboard userDashboard=new UserDashboard();
            userDashboard.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePssword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePssword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePssword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePssword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePssword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel close;
    private javax.swing.JPasswordField cnfmPwd;
    private javax.swing.JLabel error;
    private javax.swing.JLabel hideOld;
    private javax.swing.JLabel hidenew;
    private javax.swing.JLabel hidenew1;
    private javax.swing.JTextField id;
    private javax.swing.JLabel img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel logout;
    private javax.swing.JPasswordField newpwd;
    private javax.swing.JPasswordField oldPwd;
    private javax.swing.JLabel title;
    private javax.swing.JButton update;
    private javax.swing.JLabel vOld;
    private javax.swing.JLabel vnew;
    private javax.swing.JLabel vnew2;
    // End of variables declaration//GEN-END:variables

   
}
