/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import CommonTasks.RetrieveData;
import HybernetSession.HybernetSessionFctory;
import HybernetSession.HybernetSessionFctoryUser;
import Pojos.Admin;
import Pojos.Studentnstaff;
import UI.Admin.AdminDashboard;
import UI.User.UserDashboard;
import java.awt.Color;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import java.util.concurrent.atomic.AtomicReference;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Chamika
 */
public class UpdateUserProfile extends javax.swing.JFrame {

    String uId=Login.userID;
    RetrieveData retrieveData=new RetrieveData();
    public UpdateUserProfile() {
        initComponents();
        fillData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        recidence = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        error = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        img = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        title.setText("Update Profile");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 440, -1));

        lbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl1.setText("Registration ID");
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 170, 30));

        lbl2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl2.setText("Name                    ");
        jPanel1.add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 160, 20));

        lbl3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl3.setText("Email");
        jPanel1.add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        lbl4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl4.setText("Phone Number      ");
        jPanel1.add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        lbl5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl5.setText("Recidence              ");
        jPanel1.add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 160, 20));

        id.setEditable(false);
        id.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 320, -1));

        name.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 320, -1));

        email.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 320, -1));

        phone.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        phone.setText("Please enter in this format :XXX-XXXXXXX");
        phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                phoneMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                phoneMouseReleased(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 320, -1));

        recidence.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jPanel1.add(recidence, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 320, -1));

        update.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        error.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        error.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(error, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 460, 30));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeicon.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 883, Short.MAX_VALUE)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 30));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 50));

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stafreg.jpg"))); // NOI18N
        jPanel1.add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseClicked
        phone.setText("");
    }//GEN-LAST:event_phoneMouseClicked

    private void phoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseExited
        if (phone.getText().equals("")){
            phone.setForeground(Color.red);
            phone.setText("Please enter phone number..");
        }
    }//GEN-LAST:event_phoneMouseExited

    private void phoneMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneMouseReleased

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        Session usession;
        if (Login.userType.equals("user")){
            usession=HybernetSessionFctoryUser.getSessionFactory().openSession();
        }
        else{
            usession=HybernetSessionFctory.getSessionFactory().openSession();
        }
        Transaction ut=usession.beginTransaction();
        
        if (id.getText().equals("") || name.getText().equals("") || phone.getText().equals("") || email.getText().equals("") ||  phone.getText().equals("Please enter in this format :XXX-XXXXXXX")){
//            error.setForeground(Color.red);
            error.setText("Please fill all the fields..");
        }
        
        else{
            String phonePatter="\\d{3}-\\d{7}"; // pattern for phone number
            String emailPattern="[a-zA-Z].[\\w\\W]*\\.[a-zA-Z]{1,3}"; //pattern for email
            if (Pattern.compile(phonePatter).matcher(phone.getText()).matches()) { //validating phone number
                error.setText("");
                if (Pattern.compile(emailPattern).matcher(email.getText()).matches()) { // validating email address
                    error.setText("");
                    if (Login.userType.equals("admin")){
                        String usql="From Admin";
                        Query uquery=usession.createQuery(usql);
                        List<Admin> adminList=uquery.list();
                        for (Iterator<Admin> aIterator=adminList.iterator();aIterator.hasNext();){
                            Admin admin=aIterator.next();
                            if (admin.getAdminId().equals(Login.userID)){
                                String mail=admin.getEmail();
                                admin.setName(name.getText());
                                admin.setEmail(email.getText());
                                admin.setTele(phone.getText());
                                
                                
                                
                                //genearating random String
                                String generatedString=retrieveData.generateRandomString();
                                
                                Email.SendEmails.VerifyIdentity(generatedString,mail);
                                error.setText("Verification code will be sent to your email.....");
                                JFrame frame = new JFrame();
                                String rnum = JOptionPane.showInputDialog(frame, "We have send you a verification code to your email. Please enter the verification code :");
                                
                                if (rnum!=null){
                                    error.setText("");
                                    if (rnum.equals(generatedString)){
                                        usession.save(admin);
                                        usession.getTransaction().commit();
                                        JOptionPane.showMessageDialog(null, "Details updated successfully", "Successful", JOptionPane.INFORMATION_MESSAGE);
                                        AdminDashboard dash=new AdminDashboard();
                                        dash.setVisible(true);
                                        this.dispose();
                                    }
                                    else{
                                        error.setText("Invalid confirmation code");
                                    }
                                    
                                }
//                                
                                
                            }

                        }
                      
                    }
                    
                    else if(Login.userType.equals("user")){
                        String usql="From Studentnstaff";
                        Query uquery=usession.createQuery(usql);
                        List<Studentnstaff> stList=uquery.list();
                        for (Iterator<Studentnstaff> sIterator=stList.iterator();sIterator.hasNext();){
                            Studentnstaff st=sIterator.next();
                            if (st.getRegNo().equals(Login.userID)){
                                String mail=st.getEmail();
                                st.setName(name.getText());
                                st.setEmail(email.getText());
                                st.setTele(phone.getText());
                                st.setResidence(recidence.getText());
                                
                                
                                
                                //genearating random String
                                String generatedString=retrieveData.generateRandomString();
                                
                                Email.SendEmails.VerifyIdentity(generatedString,mail);
                                error.setText("Verification code will be sent to your email.....");
                                JFrame frame = new JFrame();
                                String rnum = JOptionPane.showInputDialog(frame, "We have send you a verification code to your email. Please enter the verification code :");
                                
                                if (rnum!=null){
                                    error.setText("");
                                    if (rnum.equals(generatedString)){
                                        usession.save(st);
                                        usession.getTransaction().commit();
                                        JOptionPane.showMessageDialog(null, "Details updated successfully", "Successful", JOptionPane.INFORMATION_MESSAGE);
                                        UserDashboard Udash=new UserDashboard();
                                        Udash.setVisible(true);
                                        this.dispose();
                                    }
                                    else{
                                        error.setText("Invalid confirmation code");
                                    }
                                    
                                }
//                                
                                
                            }

                        }
                        
                    }
                    
                }
                else{
                    error.setText("Invalid email address..");
                }
                
            }
            else{
                error.setText("Invalid phone number..");
            }
            
        }
        
       
//        studentnstaff
//         

        
    }//GEN-LAST:event_updateMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login log=new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        if (Login.userType.equals("admin")){
            AdminDashboard adminDashboard=new AdminDashboard();
            adminDashboard.setVisible(true);
            this.dispose();
        }
        else if (Login.userType.equals("user")){
            UserDashboard userDashboard=new UserDashboard();
            userDashboard.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateUserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateUserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateUserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateUserProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateUserProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel close;
    private javax.swing.JTextField email;
    private javax.swing.JLabel error;
    private javax.swing.JTextField id;
    private javax.swing.JLabel img;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel logout;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField recidence;
    private javax.swing.JLabel title;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void fillData() {
        
        Session session=HybernetSessionFctory.getSessionFactory().openSession();
        Transaction t=session.beginTransaction();
        AtomicReference<ResultSet> userData=new AtomicReference<>();
        session.doWork(connection->{
            try (CallableStatement cst=connection.prepareCall("{ call getUserData(?)}")){
                cst.setString(1, uId);
                cst.execute();
                userData.set(cst.getResultSet());
                try (ResultSet rs=cst.getResultSet()) {
                    while (rs.next()){
                        if (Login.userType.equals("admin")){
                            //System.out.println(rs.getString("adminID"));
                            id.setText(rs.getString("adminID"));
                            name.setText(rs.getString("name"));
                            email.setText(rs.getString("email"));
                            phone.setText(rs.getString("tele"));
                            lbl5.setVisible(false);
                            recidence.setVisible(false);
                           
                            
                        }
                        else if (Login.userType.equals("user")){
                            //System.out.println(rs.getString("reg_no"));
                            id.setText(rs.getString("reg_no"));
                            name.setText(rs.getString("name"));
                            email.setText(rs.getString("email"));
                            phone.setText(rs.getString("tele"));
                            recidence.setText(rs.getString("residence"));
                            lbl5.setVisible(true);
                            recidence.setVisible(true);
                        }
                    }
                    
                   
                    
                } catch (Exception e) {
                    System.out.println("e1"+e);
                }
                
            } catch (Exception e) {
                System.out.println("e2"+e);
            }
        
        });
    }
    
   
}
