/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;


import CommonTasks.RemovingData;
import UI.User.MyCart;
import CommonTasks.AddToCart;
import HybernetSession.HybernetSessionFctory;
import Pojos.Itemtype;
import UI.Admin.AdminDashboard;
import CommonTasks.AddItemToBuyList;
import HybernetSession.HybernetSessionFctoryUser;
import UI.User.AddOrders;
import UI.User.UserDashboard;
import UI.User.ViewBuyingList;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;


public class ViewItems extends javax.swing.JFrame {
    int height=10;
    int iTID;
    int itCount=-1;
   

    

    
    public ViewItems() {
        initComponents();
        if(Login.userType.equals("admin")){
            cartIcon.setVisible(false);
            buyListIcon.setVisible(false);
            
        }
        else if(Login.userType.equals("user")){
            cartIcon.setVisible(true);
            buyListIcon.setVisible(true);
        }
        fillCombo();
        
       
        showAllItems();
        
        //showAllItems();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        background = new javax.swing.JPanel();
        itype = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        reset = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        cartIcon = new javax.swing.JLabel();
        buyListIcon = new javax.swing.JLabel();
        imgLayer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(background);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 930, 350));

        itype.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        itype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type" }));
        itype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itypeActionPerformed(evt);
            }
        });
        jPanel1.add(itype, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 270, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Item List ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 320, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 50, 50));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("  Filter Options");
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, 30));

        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resetMouseClicked(evt);
            }
        });
        jPanel1.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 30, 30));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/closeicon.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });

        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        cartIcon.setBackground(new java.awt.Color(255, 204, 204));
        cartIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/crt (2).png"))); // NOI18N
        cartIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cartIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cartIconMouseExited(evt);
            }
        });

        buyListIcon.setBackground(new java.awt.Color(255, 204, 204));
        buyListIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buy.png"))); // NOI18N
        buyListIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buyListIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buyListIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buyListIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 809, Short.MAX_VALUE)
                .addComponent(buyListIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cartIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(logout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cartIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buyListIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 30));

        imgLayer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.jpeg"))); // NOI18N
        jPanel1.add(imgLayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        Login log=new Login();
        log.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        if (Login.userType.equals("admin")){
            AdminDashboard adminDashboard=new AdminDashboard();
            adminDashboard.setVisible(true);
            this.dispose();
        }
        else if (Login.userType.equals("user")){
            UserDashboard userDashboard=new UserDashboard();
            userDashboard.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_backMouseClicked

    private void itypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itypeActionPerformed
        if (itype.getSelectedIndex()==0){
            showAllItems();
        }
        else{
         showItemsAcType(itype.getSelectedItem().toString());  
        }
    }//GEN-LAST:event_itypeActionPerformed

    private void resetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMouseClicked
        itype.setSelectedIndex(0);
        showAllItems();
    }//GEN-LAST:event_resetMouseClicked

    private void cartIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartIconMouseClicked
        MyCart myCart=new MyCart();
        myCart.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cartIconMouseClicked

    private void cartIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartIconMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cartIconMouseEntered

    private void cartIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartIconMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_cartIconMouseExited

    private void buyListIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyListIconMouseClicked
        ViewBuyingList viewBuyingList=new ViewBuyingList();
        viewBuyingList.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buyListIconMouseClicked

    private void buyListIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyListIconMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_buyListIconMouseEntered

    private void buyListIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buyListIconMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_buyListIconMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewItems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewItems().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JPanel background;
    private javax.swing.JLabel buyListIcon;
    private javax.swing.JLabel cartIcon;
    private javax.swing.JLabel close;
    private javax.swing.JLabel imgLayer;
    private javax.swing.JComboBox<String> itype;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel reset;
    // End of variables declaration//GEN-END:variables

    public void fillCombo(){
        Session tsession;
        if (Login.userType.equals("user")){
            tsession=HybernetSessionFctoryUser.getSessionFactory().openSession();
        }
        else{
            tsession=HybernetSessionFctory.getSessionFactory().openSession();
        }
        Transaction t=tsession.beginTransaction();
        
        String sql="FROM Itemtype";
        Query query=tsession.createQuery(sql);
        List <Itemtype> typeList=query.list();
        for (Iterator<Itemtype> typeI=typeList.iterator();typeI.hasNext();){
            Itemtype itmType=typeI.next();
            itype.addItem(itmType.getName());
        }
        
        
    }
    

    private void showAllItems() {
        
        background.removeAll();
        height=60;
        setTitle();
        Session session;
        if (Login.userType.equals("user")){
            session=HybernetSessionFctoryUser.getSessionFactory().openSession();
        }
        else{
            session=HybernetSessionFctory.getSessionFactory().openSession();
        }
        final AtomicReference<ResultSet> items=new AtomicReference<>();
        session.doWork(connection->{
            try(CallableStatement cst=connection.prepareCall(
                    "{ call getItemList ()}" )){
                
                
                cst.execute();
                items.set(cst.getResultSet());
                
                try(ResultSet rs =cst.getResultSet()){
                    while(rs.next()){
                        

                        JPanel addPanal = new JPanel();
                        JLabel itmName = new JLabel();
                        JLabel itmPrice = new JLabel();
                        JLabel itmQuantity = new JLabel();
                        JLabel itmID=new JLabel();
                        JButton more = new JButton();
                        JButton addToCart = new JButton();
                        JButton order = new JButton();
                        JButton edit = new JButton();
                        JButton delete = new JButton();
                        JButton addToBuyList = new JButton();
                        

                        addPanal.setBackground(new java.awt.Color(102,204,255));
                        //addPanal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                        addPanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                        itmName.setBackground(new java.awt.Color(204, 255, 255));
                        itmName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                        //itmName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                        itmName.setOpaque(true);


                        itmPrice.setBackground(new java.awt.Color(204, 255, 255));
                        itmPrice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                       // itmPrice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                        itmPrice.setOpaque(true);


                        itmQuantity.setBackground(new java.awt.Color(204, 255, 255));
                        itmQuantity.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                        itmQuantity.setOpaque(true);


                        more.setBackground(new java.awt.Color(204, 255, 255));
                        more.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                        more.setText("More Info>>");
               
                        addToCart.setBackground(new java.awt.Color(255, 255, 255));
                        addToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N


                        order.setBackground(new java.awt.Color(255, 255, 255));
                        order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/order.png"))); // NOI18N
                        
                        addToBuyList.setBackground(new java.awt.Color(255, 255, 255));
                        addToBuyList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buy.png"))); // NOI18N

                        edit.setBackground(new java.awt.Color(255, 255, 255));
                        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.jpg"))); // NOI18N

                        delete.setBackground(new java.awt.Color(255, 255, 255));
                        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
                           
                        itmID.setText(rs.getString("id"));
                        itmName.setText(rs.getString("name"));
                        itmPrice.setText(rs.getString("price"));
                        itmQuantity.setText(rs.getString("count"));
                        
                        more.addMouseListener(new MouseAdapter() {                                
                            @Override
                            public void mouseClicked(MouseEvent e){
                                iTID=Integer.parseInt(itmID.getText());
                                ItemDescriptions itemDescriptions=new ItemDescriptions(iTID,"m");
                                itemDescriptions.setVisible(true);
                                FrameDispose(); 
                               
                                
                            }
                        });
                        
                        
                        
                        
                        edit.addMouseListener(new MouseAdapter() {                                
                            @Override
                            public void mouseClicked(MouseEvent e){
                                iTID=Integer.parseInt(itmID.getText());
                                ItemDescriptions itemDescriptions=new ItemDescriptions(iTID);
                                itemDescriptions.setVisible(true);
                                FrameDispose(); 
                                
                            }
                        });
                      
                        delete.addMouseListener(new MouseAdapter() {                                
                                @Override
                                public void mouseClicked(MouseEvent e){
                                    iTID=Integer.parseInt(itmID.getText());
                                    RemovingData removeData=new RemovingData();
                                    removeData.deleteItem(iTID);
                                    itype.setSelectedIndex(0);
                                    showAllItems();

                                }
                        });
                      
                        addToCart.addMouseListener(new MouseAdapter() {                                
                                @Override
                                public void mouseClicked(MouseEvent e){
                                    iTID=Integer.parseInt(itmID.getText());
                                    JFrame frame=new JFrame();
                                    String in=JOptionPane.showInputDialog(frame,"Enter the amount you need (Enter in numbers): ");
                                    
                                    if(in!=null){
                                        int amnt=Integer.parseInt(in);
                                        AddToCart.addToCart(iTID,amnt,"i");
                                        MyCart cart=new MyCart();
                                        cart.setVisible(true);
                                        FrameDispose();
                                    }
                                    

                                }
                        });
                        
                        addToBuyList.addMouseListener(new MouseAdapter() {                                
                                @Override
                                public void mouseClicked(MouseEvent e){
                                    iTID=Integer.parseInt(itmID.getText());
                                    JFrame frame=new JFrame();
                                    String in=JOptionPane.showInputDialog(frame,"Enter the amount you need (Enter in numbers): ");
                                    
                                    if(in!=null){
                                        int amnt=Integer.parseInt(in);
                                        if (Integer.parseInt(itmQuantity.getText())==0 || amnt>Integer.parseInt(itmQuantity.getText())){
                                            JOptionPane.showMessageDialog(null, "Sorry, This item or quantity you ordered is not available ", "Error", JOptionPane.ERROR_MESSAGE);
                                        }
                                        else{
                                            AddItemToBuyList addItemToBuyList=new AddItemToBuyList();
                                            addItemToBuyList.addToBuyList(iTID,Float.parseFloat(itmPrice.getText()), amnt, "i");
                                            ViewBuyingList bList=new ViewBuyingList();
                                            bList.setVisible(true);
                                            FrameDispose();
                                        }
                                    }
                                    

                                }
                        });
                        
                        order.addMouseListener(new MouseAdapter() {                                
                            @Override
                            public void mouseClicked(MouseEvent e){
                                iTID=Integer.parseInt(itmID.getText());
                                JFrame frame=new JFrame();
                                String in=JOptionPane.showInputDialog(frame,"Enter the amount you need (Enter in numbers): ");

                                if(in!=null){
                                    int amnt=Integer.parseInt(in);
                                    if (Integer.parseInt(itmQuantity.getText())==0 || amnt>Integer.parseInt(itmQuantity.getText())){
                                        JOptionPane.showMessageDialog(null, "Sorry, This item or quantity you ordered is not available ", "Error", JOptionPane.ERROR_MESSAGE);
                                    }
                                    else{
                                        AddOrders addOrders=new AddOrders(iTID, amnt, Float.parseFloat(itmPrice.getText())* amnt, Float.parseFloat(itmPrice.getText()),"i","i");
                                        addOrders.setVisible(true);
                                        FrameDispose();
                                    }
                                }


                            }
                        });
                        
                        
                        addPanal.add(itmName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 40));
                        addPanal.add(itmPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 100, 40));
                        addPanal.add(itmQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 150, 40));
                        addPanal.add(more, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 180, 40));
                        if (Login.userType.equals("admin")){
                            addPanal.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 40, 40));
                            addPanal.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 40, 40));
                            
                        }

                        else if (Login.userType.equals("user")){
                            addPanal.add(addToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 40, 40));
                            addPanal.add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 40, 40));
                            addPanal.add(addToBuyList, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 40, 40));
                        }
                        
                        
                        background.add(addPanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, height, 910, 60));
                        height=height+55;
                        
                        background.setVisible(false);
                        background.setVisible(true);
                     
                        
                    }
                }
                catch (Exception ex) {
                    System.out.println(ex);
                    
                }                
            }
            catch (Exception e){
                System.out.println(e);
            }
        });
    }
    
    
    

    private void showItemsAcType(String tNmae) {
        
        
        height=60;
        background.removeAll();
        setTitle();
        Session session;
        
        if (Login.userType.equals("user")){
            session=HybernetSessionFctoryUser.getSessionFactory().openSession();
        }
        else{
            session=HybernetSessionFctory.getSessionFactory().openSession();
        }
        final AtomicReference<ResultSet> items=new AtomicReference<>();
        session.doWork(connection->{
            try(CallableStatement cst=connection.prepareCall(
                    "{ call getItemListAcType (?)}" )){
               cst.setString(1, tNmae);
                
                cst.execute();
                items.set(cst.getResultSet());
                
                try(ResultSet rs =cst.getResultSet()){
                    if (rs.next()==false){
                        
                        background.removeAll();
                        background.setVisible(false);
                        background.setVisible(true);
                        itype.setVisible(false);
                        itype.setVisible(true);
                    }
                    else{
                        do{
                            JPanel addPanal = new JPanel();
                            JLabel itmName = new JLabel();
                            JLabel itmPrice = new JLabel();
                            JLabel itmQuantity = new JLabel();
                            JLabel itmID = new JLabel();
                            JButton more = new JButton();
                            JButton addToCart = new JButton();
                            JButton order = new JButton();
                            JButton edit = new JButton();
                            JButton delete = new JButton();
                            JButton addToBuyList=new JButton();
                            

                            addPanal.setBackground(new java.awt.Color(102, 204, 255));
                            //addPanal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                            addPanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                            itmName.setBackground(new java.awt.Color(204, 255, 255));
                            itmName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                            //itmName.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                            itmName.setOpaque(true);


                            itmPrice.setBackground(new java.awt.Color(204, 255, 255));
                            itmPrice.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                           // itmPrice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                            itmPrice.setOpaque(true);


                            itmQuantity.setBackground(new java.awt.Color(204, 255, 255));
                            itmQuantity.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                            itmQuantity.setOpaque(true);


                            more.setBackground(new java.awt.Color(204, 255, 255));
                            more.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
                            more.setText("More Info>>");
                            
                            addToCart.setBackground(new java.awt.Color(255, 255, 255));
                            addToCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cart.png"))); // NOI18N


                            order.setBackground(new java.awt.Color(255, 255, 255));
                            order.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/order.png"))); // NOI18N
                            
                            addToBuyList.setBackground(new java.awt.Color(255, 255, 255));
                            addToBuyList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buy.png"))); // NOI18N
                        
                            edit.setBackground(new java.awt.Color(255, 255, 255));
                            edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.jpg"))); // NOI18N
                            
                            delete.setBackground(new java.awt.Color(255, 255, 255));
                            delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N


                            itmID.setText(rs.getString("id"));
                            itmName.setText(rs.getString("name"));
                            itmPrice.setText(rs.getString("price"));
                            itmQuantity.setText(rs.getString("count"));
                            iTID=Integer.parseInt(itmID.getText());
                            more.addMouseListener(new MouseAdapter() {                                
                                @Override
                                public void mouseClicked(MouseEvent e){
                                    
                                    String user=Login.userType;
                                    ItemDescriptions itemDescriptions=new ItemDescriptions(iTID,"m");
                                    itemDescriptions.setVisible(true);
                                    FrameDispose();  
                                    
                                }
                            });
                            
                           
                            edit.addMouseListener(new MouseAdapter() {                                
                                @Override
                                public void mouseClicked(MouseEvent e){
                                    iTID=Integer.parseInt(itmID.getText());
                                    ItemDescriptions itemDescriptions=new ItemDescriptions(iTID);
                                    itemDescriptions.setVisible(true);
                                    FrameDispose(); 

                                }
                            });
                      
                            delete.addMouseListener(new MouseAdapter() {                                
                                @Override
                                public void mouseClicked(MouseEvent e){
                                    iTID=Integer.parseInt(itmID.getText());
                                    RemovingData removeData=new RemovingData();
                                    removeData.deleteItem(iTID);
                                    itype.setSelectedIndex(0);
                                    showAllItems();

                                }
                            });
                            
                            addToCart.addMouseListener(new MouseAdapter() {                                
                                @Override
                                public void mouseClicked(MouseEvent e){
                                    iTID=Integer.parseInt(itmID.getText());
                                    JFrame frame=new JFrame();
                                    
                                    String in=JOptionPane.showInputDialog(frame,"Enter the amount you need (Enter in numbers): ");
                                    
                                    if(in!=null){
                                        int amnt=Integer.parseInt(in);
                                        AddToCart.addToCart(iTID,amnt,"i");
                                        MyCart cart=new MyCart();
                                        cart.setVisible(true);
                                        FrameDispose();
                                    }

                                }
                            });
                            
                            addToBuyList.addMouseListener(new MouseAdapter() {                                
                                @Override
                                public void mouseClicked(MouseEvent e){
                                    iTID=Integer.parseInt(itmID.getText());
                                    JFrame frame=new JFrame();
                                    String in=JOptionPane.showInputDialog(frame,"Enter the amount you need (Enter in numbers): ");
                                    
                                    if(in!=null){
                                        int amnt=Integer.parseInt(in);
                                        if (Integer.parseInt(itmQuantity.getText())==0 || amnt>Integer.parseInt(itmQuantity.getText())){
                                            JOptionPane.showMessageDialog(null, "Sorry, This item or quantity you ordered is not available ", "Error", JOptionPane.ERROR_MESSAGE);
                                        }
                                        else{
                                            AddItemToBuyList addItemToBuyList=new AddItemToBuyList();
                                            addItemToBuyList.addToBuyList(iTID,Float.parseFloat(itmPrice.getText()), amnt, "i");
                                            ViewBuyingList bList=new ViewBuyingList();
                                            bList.setVisible(true);
                                            FrameDispose();
                                        }
                                    }
                                    

                                }
                            });
                        
                            
                            order.addMouseListener(new MouseAdapter() {                                
                                @Override
                                public void mouseClicked(MouseEvent e){
                                    iTID=Integer.parseInt(itmID.getText());
                                    JFrame frame=new JFrame();
                                    String in=JOptionPane.showInputDialog(frame,"Enter the amount you need (Enter in numbers): ");
                                    
                                    if(in!=null){
                                        int amnt=Integer.parseInt(in);
                                        if (Integer.parseInt(itmQuantity.getText())==0 || amnt>Integer.parseInt(itmQuantity.getText())){
                                            JOptionPane.showMessageDialog(null, "Sorry, This item or quantity you ordered is not available ", "Error", JOptionPane.ERROR_MESSAGE);
                                        }
                                        else{
                                            AddOrders addOrders=new AddOrders(iTID, amnt, Float.parseFloat(itmPrice.getText())* amnt, Float.parseFloat(itmPrice.getText()),"i","i");
                                            addOrders.setVisible(true);
                                            FrameDispose();
                                        }
                                    }
                                    

                                }
                            });
                            
                            addPanal.add(itmName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 40));
                            addPanal.add(itmPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 100, 40));
                            addPanal.add(itmQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 150, 40));
                            addPanal.add(more, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 180, 40));
                            
                            if (Login.userType.equals("admin")){
                                addPanal.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 40, 40));
                                addPanal.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 40, 40));
                                
                            }
                            
                            else if (Login.userType.equals("user")){
                                addPanal.add(addToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, 40, 40));
                                addPanal.add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 40, 40));
                                addPanal.add(addToBuyList, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 40, 40));
                            }
                            
                            
                            background.add(addPanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, height, 910, 60));
                            height=height+55;

                            background.setVisible(false);
                            background.setVisible(true);
                            
                        }while(rs.next());
                       
                    }
                       
                        
                    
                }
                catch (Exception ex) {
                    System.out.println(ex);
                    
                }                
            }
            catch (Exception e){
                System.out.println(e);
            }
        });
    }

    
   public void FrameDispose(){
       this.dispose();
   }
    
   
    
    public void setTitle(){
        JPanel titlePanal = new JPanel();
        JLabel titleItem1 = new JLabel();
        JLabel titleItem2 = new JLabel();
        JLabel titleItem3 = new JLabel();

        titlePanal.setBackground(new java.awt.Color(255, 255, 255));
        titlePanal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleItem1.setBackground(new java.awt.Color(102, 204, 255));
        titleItem1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titleItem1.setText("                    Item Name");
        titleItem1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        titleItem1.setOpaque(true);
        titlePanal.add(titleItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 290, 40));

        titleItem2.setBackground(new java.awt.Color(102, 204, 255));
        titleItem2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titleItem2.setText("    Price");
        titleItem2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        titleItem2.setOpaque(true);
        titlePanal.add(titleItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 100, 40));

        titleItem3.setBackground(new java.awt.Color(102, 204, 255));
        titleItem3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        titleItem3.setText("Available Quantity");
        titleItem3.setOpaque(true);
        titlePanal.add(titleItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 150, 40));

        background.add(titlePanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 910, 50));
    }
    

  
    

    
    
}
