package StudentNstaffPojos;
// Generated Jul 1, 2021 10:29:44 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer id;
     private String userId;
     private int itemId;
     private int count;
     private Date addedDate;
     private String type;

    public Cart() {
    }

    public Cart(String userId, int itemId, int count, Date addedDate, String type) {
       this.userId = userId;
       this.itemId = itemId;
       this.count = count;
       this.addedDate = addedDate;
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


