package StudentNstaffPojos;
// Generated Jul 1, 2021 10:29:44 PM by Hibernate Tools 4.3.1



/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String description;
     private float price;
     private int count;
     private byte[] image;
     private int mdlId;
     private int typeId;

    public Item() {
    }

	
    public Item(String name, String description, float price, int count, int mdlId, int typeId) {
        this.name = name;
        this.description = description;
        this.price = price;
        this.count = count;
        this.mdlId = mdlId;
        this.typeId = typeId;
    }
    public Item(String name, String description, float price, int count, byte[] image, int mdlId, int typeId) {
       this.name = name;
       this.description = description;
       this.price = price;
       this.count = count;
       this.image = image;
       this.mdlId = mdlId;
       this.typeId = typeId;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public int getCount() {
        return this.count;
    }
    
    public void setCount(int count) {
        this.count = count;
    }
    public byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }
    public int getMdlId() {
        return this.mdlId;
    }
    
    public void setMdlId(int mdlId) {
        this.mdlId = mdlId;
    }
    public int getTypeId() {
        return this.typeId;
    }
    
    public void setTypeId(int typeId) {
        this.typeId = typeId;
    }




}


