package StudentNstaffPojos;
// Generated Jul 1, 2021 10:29:44 PM by Hibernate Tools 4.3.1



/**
 * Meals generated by hbm2java
 */
public class Meals  implements java.io.Serializable {


     private Integer id;
     private String foodName;
     private String description;
     private String type;
     private int price;
     private String availability;
     private byte[] picture;

    public Meals() {
    }

	
    public Meals(String foodName, String description, String type, int price, String availability) {
        this.foodName = foodName;
        this.description = description;
        this.type = type;
        this.price = price;
        this.availability = availability;
    }
    public Meals(String foodName, String description, String type, int price, String availability, byte[] picture) {
       this.foodName = foodName;
       this.description = description;
       this.type = type;
       this.price = price;
       this.availability = availability;
       this.picture = picture;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFoodName() {
        return this.foodName;
    }
    
    public void setFoodName(String foodName) {
        this.foodName = foodName;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public String getAvailability() {
        return this.availability;
    }
    
    public void setAvailability(String availability) {
        this.availability = availability;
    }
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }




}


