package StudentNstaffPojos;
// Generated Jul 1, 2021 10:29:44 PM by Hibernate Tools 4.3.1



/**
 * Model generated by hbm2java
 */
public class Model  implements java.io.Serializable {


     private Integer id;
     private String name;
     private int type;

    public Model() {
    }

    public Model(String name, int type) {
       this.name = name;
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }




}


