package StudentNstaffPojos;
// Generated Jul 1, 2021 10:29:44 PM by Hibernate Tools 4.3.1



/**
 * MonthlySales generated by hbm2java
 */
public class MonthlySales  implements java.io.Serializable {


     private Integer id;
     private int amount;
     private int month;

    public MonthlySales() {
    }

    public MonthlySales(int amount, int month) {
       this.amount = amount;
       this.month = month;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public int getMonth() {
        return this.month;
    }
    
    public void setMonth(int month) {
        this.month = month;
    }




}


