package Pojos;
// Generated Jul 1, 2021 10:20:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Buylist generated by hbm2java
 */
public class Buylist  implements java.io.Serializable {


     private Integer id;
     private String userId;
     private int itmId;
     private String type;
     private float price;
     private int quantity;
     private float subTotal;
     private Date addedDate;

    public Buylist() {
    }

	
    public Buylist(String userId, int itmId, String type, float price, int quantity, float subTotal) {
        this.userId = userId;
        this.itmId = itmId;
        this.type = type;
        this.price = price;
        this.quantity = quantity;
        this.subTotal = subTotal;
    }
    public Buylist(String userId, int itmId, String type, float price, int quantity, float subTotal, Date addedDate) {
       this.userId = userId;
       this.itmId = itmId;
       this.type = type;
       this.price = price;
       this.quantity = quantity;
       this.subTotal = subTotal;
       this.addedDate = addedDate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    public int getItmId() {
        return this.itmId;
    }
    
    public void setItmId(int itmId) {
        this.itmId = itmId;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public float getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(float subTotal) {
        this.subTotal = subTotal;
    }
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }




}


