package Pojos;
// Generated Jul 1, 2021 10:20:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * YearlySales generated by hbm2java
 */
public class YearlySales  implements java.io.Serializable {


     private Integer id;
     private int amount;
     private Date year;

    public YearlySales() {
    }

    public YearlySales(int amount, Date year) {
       this.amount = amount;
       this.year = year;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getAmount() {
        return this.amount;
    }
    
    public void setAmount(int amount) {
        this.amount = amount;
    }
    public Date getYear() {
        return this.year;
    }
    
    public void setYear(Date year) {
        this.year = year;
    }




}


